using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using SourceGenerator.Core.Internal;

namespace SourceGenerator.Core;

internal sealed class ClassProxyHandler
{
    private const string ProxyBehaviorAttributeMetadataName = "SourceGenerator.Abstraction.Attributes.ProxyBehaviorAttribute";

    public bool CanHandle(INamedTypeSymbol type, AttributeData? attribute)
        => type.TypeKind == TypeKind.Class;

    public void Execute(in HandlerContext ctx)
    {
        var src = GenerateDerivedProxy(ctx.Type);
        var hint = GetSafeHintName(ctx.Type) + ".g.cs";
        ctx.Context.AddSource(hint, src);
    }

    private static string GenerateDerivedProxy(INamedTypeSymbol cls)
    {
        var ns = cls.ContainingNamespace.IsGlobalNamespace
            ? "NetEngine.Generated"
            : cls.ContainingNamespace.ToDisplayString();

        var classDisplay = cls.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
        var classFull = cls.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", string.Empty);
        var proxyName = cls.Name + "_Proxy";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.Append("namespace ").Append(ns).AppendLine(";");
        sb.AppendLine();

        // helpers
        sb.Append("file static class __ProxyHelpers_").Append(proxyName).AppendLine(" {");
        sb.AppendLine("    internal static string ArgToString(object? o)");
        sb.AppendLine("    {");
        sb.AppendLine("        return global::SourceGenerator.Runtime.JsonUtil.ToJson(o);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // proxy class derives from original implementation and re-lists implemented interfaces
        var ifaceList = cls.AllInterfaces.Length == 0 ? string.Empty : ", " + string.Join(", ", cls.AllInterfaces.Select(i => i.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)));
        sb.Append("public sealed class ").Append(proxyName).Append(" : ").Append(classDisplay).Append(ifaceList).AppendLine()
          .AppendLine("{")
          .AppendLine("    private readonly global::System.IServiceProvider? __sp;")
          .AppendLine();

        // constructors: mirror base public/protected ctors; also add overloads with IServiceProvider if not already leading
        foreach (var ctor in cls.Constructors)
        {
            if (ctor.DeclaredAccessibility != Accessibility.Public && ctor.DeclaredAccessibility != Accessibility.Protected)
                continue;

            var paramList = string.Join(", ", ctor.Parameters.Select(FormatParameter));
            var argList = string.Join(", ", ctor.Parameters.Select(p => p.Name));
            // plain mirror
            sb.Append("    public ").Append(proxyName).Append('(').Append(paramList).Append(')').AppendLine()
              .AppendLine("        : base(" + argList + ")")
              .AppendLine("    {")
              .AppendLine("    }")
              .AppendLine();

            // IServiceProvider-leading overload if first param is not IServiceProvider
            var firstIsSp = ctor.Parameters.FirstOrDefault() is IParameterSymbol fp && IsType(fp.Type, "System.IServiceProvider");
            if (!firstIsSp)
            {
                var withSpParams = (ctor.Parameters.Length == 0)
                    ? "global::System.IServiceProvider sp"
                    : "global::System.IServiceProvider sp, " + paramList;
                sb.Append("    public ").Append(proxyName).Append('(').Append(withSpParams).Append(')').AppendLine()
                  .AppendLine("        : base(" + argList + ")")
                  .AppendLine("    {")
                  .AppendLine("        __sp = sp;")
                  .AppendLine("    }")
                  .AppendLine();
            }
        }

        // override virtual/abstract public instance methods
        foreach (var method in cls.GetMembers().OfType<IMethodSymbol>())
        {
            if (method.MethodKind is MethodKind.PropertyGet or MethodKind.PropertySet or MethodKind.EventAdd or MethodKind.EventRemove or MethodKind.EventRaise or MethodKind.StaticConstructor or MethodKind.Constructor)
                continue;
            if (method.DeclaredAccessibility != Accessibility.Public || method.IsStatic)
                continue;
            if (!(method.IsVirtual || method.IsAbstract || method.IsOverride))
                continue;
            if (method.Parameters.Any(p => p.RefKind != RefKind.None))
                continue;
            AppendDerivedOverride(sb, method, classFull, callTarget: "base");
        }

        // explicit interface implementations to intercept when used via interface
        foreach (var iface in cls.AllInterfaces)
        {
            foreach (var member in iface.GetMembers())
            {
                switch (member)
                {
                    case IMethodSymbol m:
                        if (m.MethodKind is MethodKind.PropertyGet or MethodKind.PropertySet or MethodKind.EventAdd or MethodKind.EventRemove or MethodKind.EventRaise)
                            continue;
                        if (m.Parameters.Any(p => p.RefKind != RefKind.None))
                            continue;
                        // find implementation in class
                        var impl = cls.FindImplementationForInterfaceMember(m) as IMethodSymbol;
                        AppendExplicitInterfaceMethod(sb, iface, m, impl, classFull);
                        break;
                    case IPropertySymbol p:
                        AppendExplicitInterfaceProperty(sb, iface, p);
                        break;
                    case IEventSymbol e:
                        AppendExplicitInterfaceEvent(sb, iface, e);
                        break;
                }
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendDerivedOverride(StringBuilder sb, IMethodSymbol method, string typeFullName, string callTarget)
    {
        var isGenericTask = method.ReturnType is INamedTypeSymbol nts && nts.IsGenericType && IsType(nts.ConstructedFrom, "System.Threading.Tasks.Task");
        var isTask = method.ReturnType is INamedTypeSymbol nts0 && !nts0.IsGenericType && IsType(nts0, "System.Threading.Tasks.Task");
        var isGenericValueTask = method.ReturnType is INamedTypeSymbol nts2 && nts2.IsGenericType && IsType(nts2.ConstructedFrom, "System.Threading.Tasks.ValueTask");
        var isValueTask = method.ReturnType is INamedTypeSymbol nts3 && !nts3.IsGenericType && IsType(nts3, "System.Threading.Tasks.ValueTask");

        var returnType = method.ReturnType
            .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier));
        var methodName = method.Name;
        var typeParams = method.TypeParameters.Length > 0 ? "<" + string.Join(", ", method.TypeParameters.Select(tp => tp.Name)) + ">" : string.Empty;
        var paramList = string.Join(", ", method.Parameters.Select(FormatParameter));
        var argList = string.Join(", ", method.Parameters.Select(p => p.Name));

        sb.Append("    public override ").Append(returnType).Append(' ').Append(methodName).Append(typeParams)
          .Append('(').Append(paramList).Append(')').AppendLine()
          .AppendLine("    {");

        if (method.Parameters.Length > 0)
        {
            sb.AppendLine("        var __argsDict = new global::System.Collections.Generic.Dictionary<string, object?>(" + method.Parameters.Length + ");");
            foreach (var p in method.Parameters)
            {
                sb.Append("        __argsDict[\"").Append(p.Name).Append("\"] = ").Append(p.Name).AppendLine(";");
            }
            sb.AppendLine("        var __args = global::SourceGenerator.Runtime.JsonUtil.ToJson(__argsDict);");
        }
        else
        {
            sb.AppendLine("        string? __args = null;");
        }

        sb.AppendLine("        var __logMethod = \"" + typeFullName + "\" + \"." + methodName + "\";");
        sb.AppendLine("        var __logger = (__sp?.GetService(typeof(global::Microsoft.Extensions.Logging.ILoggerFactory)) as global::Microsoft.Extensions.Logging.ILoggerFactory)?.CreateLogger(\"SourceGenerator.Runtime.ProxyRuntime\");");

        var behaviorSnippets = new List<string> { "new global::SourceGenerator.Runtime.LoggingBehavior()" };
        var optionsSetters = new List<string>();
        foreach (var a in method.GetAttributes())
        {
            if (TryGetBehaviorSpec(a, out var behaviorFull, out var optInit))
            {
                behaviorSnippets.Add($"new {behaviorFull}()");
                if (!string.IsNullOrEmpty(optInit)) optionsSetters.Add(optInit!);
            }
        }
        sb.AppendLine("        var __behaviors = new global::SourceGenerator.Runtime.IInvocationBehavior[] { " + string.Join(", ", behaviorSnippets) + " };");
        var __hasReturn = isGenericTask || isGenericValueTask || (!isTask && !isValueTask && !method.ReturnsVoid);
        sb.AppendLine("        var __ctx = new global::SourceGenerator.Runtime.InvocationContext { Method = __logMethod, ArgsJson = __args, TraceId = global::System.Guid.CreateVersion7(), Log = true, HasReturnValue = " + (__hasReturn ? "true" : "false") + ", ServiceProvider = __sp, Logger = __logger, Behaviors = __behaviors };");
        if (optionsSetters.Count > 0) sb.AppendLine("        " + string.Join("\n        ", optionsSetters));

        var runtime = "global::SourceGenerator.Runtime.ProxyRuntime";
        if (isTask)
        {
            sb.AppendLine($"        return {runtime}.ExecuteTask(__ctx, () => {callTarget}.{methodName}{typeParams}({argList}));");
        }
        else if (isGenericTask)
        {
            var tArg = ((INamedTypeSymbol)method.ReturnType).TypeArguments[0]
                .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier));
            sb.AppendLine($"        return {runtime}.ExecuteAsync<{tArg}>(__ctx, () => new global::System.Threading.Tasks.ValueTask<{tArg}>( {callTarget}.{methodName}{typeParams}({argList}) ) ).AsTask();");
        }
        else if (isValueTask)
        {
            sb.AppendLine($"        return new global::System.Threading.Tasks.ValueTask( {runtime}.ExecuteTask(__ctx, () => {callTarget}.{methodName}{typeParams}({argList}).AsTask()) );");
        }
        else if (isGenericValueTask)
        {
            var tArg = ((INamedTypeSymbol)method.ReturnType).TypeArguments[0]
                .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier));
            sb.AppendLine($"        return new global::System.Threading.Tasks.ValueTask<{tArg}>( {runtime}.ExecuteAsync<{tArg}>(__ctx, () => {callTarget}.{methodName}{typeParams}({argList}) ).AsTask() );");
        }
        else if (method.ReturnsVoid)
        {
            sb.AppendLine($"        {runtime}.Execute<object?>(__ctx, () => {{ {callTarget}.{methodName}{typeParams}({argList}); return global::System.Threading.Tasks.ValueTask.FromResult<object?>(null); }});");
            sb.AppendLine("        return;");
        }
        else
        {
            sb.AppendLine($"        return {runtime}.Execute<{returnType}>(__ctx, () => global::System.Threading.Tasks.ValueTask.FromResult({callTarget}.{methodName}{typeParams}({argList})));");
        }

        sb.AppendLine("    }");
    }

    private static void AppendExplicitInterfaceMethod(StringBuilder sb, INamedTypeSymbol iface, IMethodSymbol method, IMethodSymbol? impl, string typeFullName)
    {
        // Build compile-time behaviors from both interface method and implementation method attributes
        var isGenericTask = method.ReturnType is INamedTypeSymbol nts && nts.IsGenericType && IsType(nts.ConstructedFrom, "System.Threading.Tasks.Task");
        var isTask = method.ReturnType is INamedTypeSymbol nts0 && !nts0.IsGenericType && IsType(nts0, "System.Threading.Tasks.Task");
        var isGenericValueTask = method.ReturnType is INamedTypeSymbol nts2 && nts2.IsGenericType && IsType(nts2.ConstructedFrom, "System.Threading.Tasks.ValueTask");
        var isValueTask = method.ReturnType is INamedTypeSymbol nts3 && !nts3.IsGenericType && IsType(nts3, "System.Threading.Tasks.ValueTask");

        var returnType = method.ReturnType
            .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier));
        var ifaceDisplay = iface.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
        var methodName = method.Name;
        var typeParams = method.TypeParameters.Length > 0 ? "<" + string.Join(", ", method.TypeParameters.Select(tp => tp.Name)) + ">" : string.Empty;
        var paramList = string.Join(", ", method.Parameters.Select(FormatParameter));
        var argList = string.Join(", ", method.Parameters.Select(p => p.Name));

        sb.Append("    ").Append(returnType).Append(' ').Append(ifaceDisplay).Append('.').Append(methodName).Append(typeParams)
          .Append('(').Append(paramList).Append(')').AppendLine()
          .AppendLine("    {");

        if (method.Parameters.Length > 0)
        {
            sb.AppendLine("        var __argsDict = new global::System.Collections.Generic.Dictionary<string, object?>(" + method.Parameters.Length + ");");
            foreach (var p in method.Parameters)
            {
                sb.Append("        __argsDict[\"").Append(p.Name).Append("\"] = ").Append(p.Name).AppendLine(";");
            }
            sb.AppendLine("        var __args = global::SourceGenerator.Runtime.JsonUtil.ToJson(__argsDict);");
        }
        else
        {
            sb.AppendLine("        string? __args = null;");
        }

        sb.AppendLine("        var __logMethod = \"" + typeFullName + "\" + \"." + methodName + "\";");
        sb.AppendLine("        var __logger = (__sp?.GetService(typeof(global::Microsoft.Extensions.Logging.ILoggerFactory)) as global::Microsoft.Extensions.Logging.ILoggerFactory)?.CreateLogger(\"SourceGenerator.Runtime.ProxyRuntime\");");

        var behaviorSnippets = new List<string> { "new global::SourceGenerator.Runtime.LoggingBehavior()" };
        var optionsSetters = new List<string>();
        foreach (var a in method.GetAttributes())
        {
            if (TryGetBehaviorSpec(a, out var behaviorFull, out var optInit))
            {
                behaviorSnippets.Add($"new {behaviorFull}()");
                if (!string.IsNullOrEmpty(optInit)) optionsSetters.Add(optInit!);
            }
        }
        if (impl is not null)
        {
            foreach (var a in impl.GetAttributes())
            {
                if (TryGetBehaviorSpec(a, out var behaviorFull, out var optInit))
                {
                    behaviorSnippets.Add($"new {behaviorFull}()");
                    if (!string.IsNullOrEmpty(optInit)) optionsSetters.Add(optInit!);
                }
            }
        }
        sb.AppendLine("        var __behaviors = new global::SourceGenerator.Runtime.IInvocationBehavior[] { " + string.Join(", ", behaviorSnippets) + " };");
        var __hasReturn = isGenericTask || isGenericValueTask || (!isTask && !isValueTask && !method.ReturnsVoid);
        sb.AppendLine("        var __ctx = new global::SourceGenerator.Runtime.InvocationContext { Method = __logMethod, ArgsJson = __args, TraceId = global::System.Guid.CreateVersion7(), Log = true, HasReturnValue = " + (__hasReturn ? "true" : "false") + ", ServiceProvider = __sp, Logger = __logger, Behaviors = __behaviors };");
        if (optionsSetters.Count > 0) sb.AppendLine("        " + string.Join("\n        ", optionsSetters));

        var runtime = "global::SourceGenerator.Runtime.ProxyRuntime";
        var call = "base." + methodName + typeParams + "(" + argList + ")";

        if (isTask)
        {
            sb.AppendLine($"        return {runtime}.ExecuteTask(__ctx, () => {call});");
        }
        else if (isGenericTask)
        {
            var tArg = ((INamedTypeSymbol)method.ReturnType).TypeArguments[0]
                .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier));
            sb.AppendLine($"        return {runtime}.ExecuteAsync<{tArg}>(__ctx, () => new global::System.Threading.Tasks.ValueTask<{tArg}>( {call} ) ).AsTask();");
        }
        else if (isValueTask)
        {
            sb.AppendLine($"        return new global::System.Threading.Tasks.ValueTask( {runtime}.ExecuteTask(__ctx, () => {call}.AsTask()) );");
        }
        else if (isGenericValueTask)
        {
            var tArg = ((INamedTypeSymbol)method.ReturnType).TypeArguments[0]
                .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier));
            sb.AppendLine($"        return new global::System.Threading.Tasks.ValueTask<{tArg}>( {runtime}.ExecuteAsync<{tArg}>(__ctx, () => {call} ).AsTask() );");
        }
        else if (method.ReturnsVoid)
        {
            sb.AppendLine($"        {runtime}.Execute<object?>(__ctx, () => {{ {call}; return global::System.Threading.Tasks.ValueTask.FromResult<object?>(null); }});");
            sb.AppendLine("        return;");
        }
        else
        {
            sb.AppendLine($"        return {runtime}.Execute<{returnType}>(__ctx, () => global::System.Threading.Tasks.ValueTask.FromResult({call}));");
        }

        sb.AppendLine("    }");
    }

    private static void AppendExplicitInterfaceProperty(StringBuilder sb, INamedTypeSymbol iface, IPropertySymbol prop)
    {
        var typeName = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var ifaceDisplay = iface.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
        sb.Append("    ").Append(typeName).Append(' ').Append(ifaceDisplay).Append('.').Append(prop.Name).AppendLine()
          .AppendLine("    {");
        if (prop.GetMethod is not null)
        {
            sb.AppendLine("        get => base." + prop.Name + ";");
        }
        if (prop.SetMethod is not null)
        {
            sb.AppendLine("        set => base." + prop.Name + " = value;");
        }
        sb.AppendLine("    }");
    }

    private static void AppendExplicitInterfaceEvent(StringBuilder sb, INamedTypeSymbol iface, IEventSymbol ev)
    {
        var typeName = ev.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var ifaceDisplay = iface.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
        sb.Append("    event ").Append(typeName).Append(' ').Append(ifaceDisplay).Append('.').Append(ev.Name).AppendLine()
          .AppendLine("    {")
          .AppendLine("        add => base." + ev.Name + " += value;")
          .AppendLine("        remove => base." + ev.Name + " -= value;")
          .AppendLine("    }");
    }

    private static bool TryGetBehaviorSpec(AttributeData a, out string behaviorFull, out string? optSetter)
    {
        behaviorFull = string.Empty;
        optSetter = null;
        var attrClass = a.AttributeClass as INamedTypeSymbol;
        if (attrClass is null) return false;
        INamedTypeSymbol? proxyBase = null;
        for (var t = attrClass; t is not null; t = t.BaseType as INamedTypeSymbol)
        {
            var constructed = t.ConstructedFrom ?? t;
            var fullName = constructed.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (fullName.Contains(ProxyBehaviorAttributeMetadataName, StringComparison.Ordinal)) { proxyBase = t; break; }
        }
        if (proxyBase is null) return false;
        ITypeSymbol? behaviorTypeSymbol = null;
        INamedTypeSymbol? optionsTypeSymbol = null;
        if (proxyBase.IsGenericType)
        {
            if (proxyBase.TypeArguments.Length == 1)
            {
                behaviorTypeSymbol = proxyBase.TypeArguments[0];
            }
            else if (proxyBase.TypeArguments.Length == 2)
            {
                behaviorTypeSymbol = proxyBase.TypeArguments[0];
                optionsTypeSymbol = proxyBase.TypeArguments[1] as INamedTypeSymbol;
            }
        }
        if (behaviorTypeSymbol is null) return false;
        behaviorFull = behaviorTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        if (optionsTypeSymbol is not null)
        {
            var assigns = new List<string>();
            foreach (var kv in a.NamedArguments)
            {
                var propName = kv.Key;
                var prop = optionsTypeSymbol.GetMembers().OfType<IPropertySymbol>().FirstOrDefault(p => p.Name == propName && !p.IsReadOnly);
                if (prop is null) continue;
                var lit = ToCSharpLiteral(kv.Value);
                if (lit is null) continue;
                assigns.Add(propName + " = " + lit);
            }
            var optFull = optionsTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var init = assigns.Count > 0 ? " { " + string.Join(", ", assigns) + " }" : string.Empty;
            optSetter = $"__ctx.SetFeature(new {optFull}{init});";
        }
        return true;
    }

    private static string FormatParameter(IParameterSymbol p)
    {
        var type = p.Type
            .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier));
        var @default = p.HasExplicitDefaultValue ? " = " + (p.ExplicitDefaultValue is null ? "null" : p.ExplicitDefaultValue is string s ? "\"" + s.Replace("\"", "\\\"") + "\"" : p.ExplicitDefaultValue.ToString()) : string.Empty;
        return type + " " + p.Name + @default;
    }

    private static bool IsType(ITypeSymbol t, string metadataName)
        => t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Contains(metadataName, StringComparison.Ordinal);

    private static string? ToCSharpLiteral(TypedConstant c)
    {
        if (c.IsNull) return "null";
        if (c.Value is null) return null;
        if (c.Value is string s) return "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
        if (c.Value is bool b) return b ? "true" : "false";
        if (c.Value is char ch) return "'" + (ch == '\'' ? "\\'" : ch.ToString()) + "'";
        if (c.Type is INamedTypeSymbol nts && nts.TypeKind == TypeKind.Enum)
        {
            var named = nts.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return named + "." + c.Value.ToString();
        }
        if (c.Value is IFormattable f) return f.ToString(null, System.Globalization.CultureInfo.InvariantCulture);
        return c.Value?.ToString();
    }

    private static string GetSafeHintName(INamedTypeSymbol type)
    {
        var ns = type.ContainingNamespace.IsGlobalNamespace ? "global" : type.ContainingNamespace.ToDisplayString().Replace('.', '_');
        return ns + "__" + type.Name + "+Proxy";
    }
}
