using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using SourceGenerator.Core.Internal;

namespace SourceGenerator.Core;

internal sealed class InterfaceProxyHandler 
{
    private const string CacheableAttributeMetadataName = "SourceGenerator.Abstraction.Attributes.CacheableAttribute";

    public bool CanHandle(INamedTypeSymbol type, AttributeData? attribute)
        => type.TypeKind == TypeKind.Interface;

    public void Execute(in HandlerContext ctx)
    {
        var source = GenerateInterfaceProxy(ctx.Type, ctx.Options);
        var hintName = GetSafeHintName(ctx.Type) + ".g.cs";
        ctx.Context.AddSource(hintName, source);
    }

    private static string GenerateInterfaceProxy(INamedTypeSymbol iface, ProxyOptionsModel options)
    {
        var ns = iface.ContainingNamespace.IsGlobalNamespace
            ? "NetEngine.Generated"
            : iface.ContainingNamespace.ToDisplayString();

        var proxyName = iface.Name + "_Proxy";
        var ifaceDisplay = iface.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.Append("namespace ").Append(ns).AppendLine(";");
        sb.AppendLine();
        sb.Append("file static class __ProxyHelpers_").Append(proxyName).AppendLine(" {");
        sb.AppendLine("    internal static string ArgToString(object? o) => o?.ToString() ?? \"<null>\";");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.Append("public sealed class ").Append(proxyName).Append(" : ").Append(ifaceDisplay).AppendLine()
          .AppendLine("{")
          .Append("    private readonly ").Append(ifaceDisplay).AppendLine(" __inner;")
          .AppendLine("    private readonly global::System.IServiceProvider? __sp;")
          .AppendLine()
          .Append("    public ").Append(proxyName).Append("(").Append(ifaceDisplay).AppendLine(" inner)")
          .AppendLine("    {")
          .AppendLine("        __inner = inner ?? throw new global::System.ArgumentNullException(nameof(inner));")
          .AppendLine("    }");

        sb.AppendLine()
          .Append("    public ").Append(proxyName).Append("(").Append(ifaceDisplay).AppendLine(" inner, global::System.IServiceProvider sp)")
          .AppendLine("    {")
          .AppendLine("        __inner = inner ?? throw new global::System.ArgumentNullException(nameof(inner));")
          .AppendLine("        __sp = sp;")
          .AppendLine("    }");

        foreach (var member in iface.GetMembers().OfType<IMethodSymbol>())
        {
            if (member.MethodKind is MethodKind.PropertyGet or MethodKind.PropertySet or MethodKind.EventAdd or MethodKind.EventRemove or MethodKind.EventRaise or MethodKind.StaticConstructor or MethodKind.Constructor)
                continue;
            if (member.DeclaredAccessibility != Accessibility.Public)
                continue;
            AppendMethod(sb, member, options);
        }

        foreach (var prop in iface.GetMembers().OfType<IPropertySymbol>())
        {
            if (prop.DeclaredAccessibility != Accessibility.Public)
                continue;
            AppendProperty(sb, prop, options);
        }

        foreach (var ev in iface.GetMembers().OfType<IEventSymbol>())
        {
            if (ev.DeclaredAccessibility != Accessibility.Public)
                continue;
            AppendEvent(sb, ev);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendEvent(StringBuilder sb, IEventSymbol ev)
    {
        var typeName = ev.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
        sb.Append("    public event ").Append(typeName).Append(' ').Append(ev.Name)
          .AppendLine()
          .AppendLine("    {")
          .AppendLine("        add => __inner." + ev.Name + " += value;")
          .AppendLine("        remove => __inner." + ev.Name + " -= value;")
          .AppendLine("    }");
    }

    private static void AppendProperty(StringBuilder sb, IPropertySymbol prop, ProxyOptionsModel options)
    {
        var typeName = prop.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
        sb.Append("    public ").Append(typeName).Append(' ').Append(prop.Name).AppendLine()
          .AppendLine("    {");
        if (prop.GetMethod is not null)
        {
            sb.Append("        get").AppendLine()
              .AppendLine("        {");
            if (options.EnableLogging)
            {
                sb.Append("            global::System.Console.WriteLine(\"[Proxy] get ")
                  .Append(prop.Name).AppendLine("\");");
            }
            sb.AppendLine("            return __inner." + prop.Name + ";")
              .AppendLine("        }");
        }
        if (prop.SetMethod is not null)
        {
            sb.Append("        set").AppendLine()
              .AppendLine("        {");
            if (options.EnableLogging)
            {
                sb.Append("            global::System.Console.WriteLine(\"[Proxy] set ")
                  .Append(prop.Name).AppendLine("\");");
            }
            sb.AppendLine("            __inner." + prop.Name + " = value;")
              .AppendLine("        }");
        }
        sb.AppendLine("    }");
    }

        private static void AppendMethod(StringBuilder sb, IMethodSymbol method, ProxyOptionsModel options)
    {
        if (method.Parameters.Any(p => p.RefKind != RefKind.None)) return;

        var isGenericTask = method.ReturnType is INamedTypeSymbol nts && nts.IsGenericType && IsType(nts.ConstructedFrom, "System.Threading.Tasks.Task");
        var isTask = method.ReturnType is INamedTypeSymbol nts0 && !nts0.IsGenericType && IsType(nts0, "System.Threading.Tasks.Task");
        var isGenericValueTask = method.ReturnType is INamedTypeSymbol nts2 && nts2.IsGenericType && IsType(nts2.ConstructedFrom, "System.Threading.Tasks.ValueTask");
        var isValueTask = method.ReturnType is INamedTypeSymbol nts3 && !nts3.IsGenericType && IsType(nts3, "System.Threading.Tasks.ValueTask");

        var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
        var methodName = method.Name;
        var typeParams = method.TypeParameters.Length > 0 ? "<" + string.Join(", ", method.TypeParameters.Select(tp => tp.Name)) + ">" : string.Empty;
        var paramList = string.Join(", ", method.Parameters.Select(FormatParameter));
        var argList = string.Join(", ", method.Parameters.Select(p => p.Name));

        var enableLogging = options.EnableLogging;

        sb.Append("    public ").Append(returnType).Append(' ').Append(methodName).Append(typeParams)
          .Append('(').Append(paramList).Append(')').AppendLine()
          .AppendLine("    {");

        if (options.CaptureArguments && method.Parameters.Length > 0)
        {
            sb.AppendLine("        var __argsList = new string[" + method.Parameters.Length + "];");
            int __i = 0;
            foreach (var p in method.Parameters)
            {
                sb.Append("        __argsList[").Append(__i).Append("] = \"")
                  .Append(p.Name).Append("=\" + __ProxyHelpers_")
                  .Append(method.ContainingType.Name + "_Proxy")
                  .Append(".ArgToString(").Append(p.Name).Append(");").AppendLine();
                __i++;
            }
            sb.AppendLine("        var __args = string.Join(\", \", __argsList);");
        }
        else
        {
            sb.AppendLine("        string? __args = null;");
        }
        var cacheAttr = method.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == CacheableAttributeMetadataName);
        var hasCache = cacheAttr is not null && !method.ReturnsVoid;
        var ttl = 60;
        if (hasCache)
        {
            foreach (var kv in cacheAttr!.NamedArguments)
            {
                if (kv.Key == "TtlSeconds" && kv.Value.Value is int i) ttl = i;
            }
            sb.AppendLine("        var __cache = new global::SourceGenerator.Runtime.ProxyRuntime.CacheOptions { Seed = \"" + methodName + "\" + (__args is null ? string.Empty : __args), TtlSeconds = " + ttl + " };");
        }
        else
        {
            sb.AppendLine("        global::SourceGenerator.Runtime.ProxyRuntime.CacheOptions? __cache = null;");
        }

        var runtime = "global::SourceGenerator.Runtime.ProxyRuntime";
        if (isTask)
        {
            sb.AppendLine($"        return {runtime}.InvokeTask(() => __inner.{methodName}{typeParams}({argList}), \"{methodName}\", {(enableLogging ? "true" : "false")}, {(options.MeasureTime ? "true" : "false")}, __args, __sp);");
        }
        else if (isGenericTask)
        {
            var tArg = ((INamedTypeSymbol)method.ReturnType).TypeArguments[0].ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
            sb.AppendLine($"        return {runtime}.InvokeTask<{tArg}>(() => __inner.{methodName}{typeParams}({argList}), \"{methodName}\", {(enableLogging ? "true" : "false")}, {(options.MeasureTime ? "true" : "false")}, __args, __sp, __cache);");
        }
        else if (isValueTask)
        {
            sb.AppendLine($"        return {runtime}.InvokeValueTask(() => __inner.{methodName}{typeParams}({argList}), \"{methodName}\", {(enableLogging ? "true" : "false")}, {(options.MeasureTime ? "true" : "false")}, __args, __sp);");
        }
        else if (isGenericValueTask)
        {
            var tArg = ((INamedTypeSymbol)method.ReturnType).TypeArguments[0].ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
            sb.AppendLine($"        return {runtime}.InvokeValueTask<{tArg}>(() => __inner.{methodName}{typeParams}({argList}), \"{methodName}\", {(enableLogging ? "true" : "false")}, {(options.MeasureTime ? "true" : "false")}, __args, __sp, __cache);");
        }
        else if (method.ReturnsVoid)
        {
            sb.AppendLine($"        {runtime}.Invoke(() => __inner.{methodName}{typeParams}({argList}), \"{methodName}\", {(enableLogging ? "true" : "false")}, {(options.MeasureTime ? "true" : "false")}, __args, __sp);");
            sb.AppendLine("        return;");
        }
        else
        {
            sb.AppendLine($"        return {runtime}.Invoke<{returnType}>(() => __inner.{methodName}{typeParams}({argList}), \"{methodName}\", {(enableLogging ? "true" : "false")}, {(options.MeasureTime ? "true" : "false")}, __args, __sp, __cache);");
        }

        sb.AppendLine("    }");
    }private static string FormatParameter(IParameterSymbol p)
    {
        var type = p.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
        var @default = p.HasExplicitDefaultValue ? " = " + (p.ExplicitDefaultValue is null ? "null" : p.ExplicitDefaultValue is string s ? "\"" + s.Replace("\"", "\\\"") + "\"" : p.ExplicitDefaultValue.ToString()) : string.Empty;
        return type + " " + p.Name + @default;
    }

    private static bool IsType(ITypeSymbol t, string metadataName)
        => t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Contains(metadataName, StringComparison.Ordinal);

    private static string GetSafeHintName(INamedTypeSymbol type)
    {
        var ns = type.ContainingNamespace.IsGlobalNamespace ? "global" : type.ContainingNamespace.ToDisplayString().Replace('.', '_');
        return ns + "__" + type.Name + "+Proxy";
    }
}










