using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using SourceGenerator.Core.Internal;

namespace SourceGenerator.Core;

internal sealed class InterfaceProxyHandler
{
    private const string ProxyBehaviorAttributeMetadataName = "SourceGenerator.Abstraction.Attributes.ProxyBehaviorAttribute";

    public bool CanHandle(INamedTypeSymbol type, AttributeData? attribute)
        => type.TypeKind == TypeKind.Interface;

    public void Execute(in HandlerContext ctx)
    {
        var source = GenerateInterfaceProxy(ctx.Type);
        var hintName = GetSafeHintName(ctx.Type) + ".g.cs";
        ctx.Context.AddSource(hintName, source);
    }

    private static string GenerateInterfaceProxy(INamedTypeSymbol iface)
    {
        var ns = iface.ContainingNamespace.IsGlobalNamespace
            ? "NetEngine.Generated"
            : iface.ContainingNamespace.ToDisplayString();

        var proxyName = iface.Name + "_Proxy";
        var ifaceDisplay = iface.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.Append("namespace ").Append(ns).AppendLine(";");
        sb.AppendLine();
        sb.Append("file static class __ProxyHelpers_").Append(proxyName).AppendLine(" {");
        sb.AppendLine("    internal static string ArgToString(object? o)");
        sb.AppendLine("    {");
        sb.AppendLine("        return global::SourceGenerator.Runtime.JsonUtil.ToJson(o);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.Append("public sealed class ").Append(proxyName).Append(" : ").Append(ifaceDisplay).AppendLine()
          .AppendLine("{")
          .Append("    private readonly ").Append(ifaceDisplay).AppendLine(" __inner;")
          .AppendLine("    private readonly global::System.IServiceProvider? __sp;")
          .AppendLine()
          .Append("    public ").Append(proxyName).Append("(").Append(ifaceDisplay).AppendLine(" inner)")
          .AppendLine("    {")
          .AppendLine("        __inner = inner ?? throw new global::System.ArgumentNullException(nameof(inner));")
          .AppendLine("    }");

        sb.AppendLine()
          .Append("    public ").Append(proxyName).Append("(").Append(ifaceDisplay).AppendLine(" inner, global::System.IServiceProvider sp)")
          .AppendLine("    {")
          .AppendLine("        __inner = inner ?? throw new global::System.ArgumentNullException(nameof(inner));")
          .AppendLine("        __sp = sp;")
          .AppendLine("    }");

        foreach (var member in iface.GetMembers().OfType<IMethodSymbol>())
        {
            if (member.MethodKind is MethodKind.PropertyGet or MethodKind.PropertySet or MethodKind.EventAdd or MethodKind.EventRemove or MethodKind.EventRaise or MethodKind.StaticConstructor or MethodKind.Constructor)
                continue;
            if (member.DeclaredAccessibility != Accessibility.Public)
                continue;
            AppendMethod(sb, member);
        }

        foreach (var prop in iface.GetMembers().OfType<IPropertySymbol>())
        {
            if (prop.DeclaredAccessibility != Accessibility.Public)
                continue;
            AppendProperty(sb, prop);
        }

        foreach (var ev in iface.GetMembers().OfType<IEventSymbol>())
        {
            if (ev.DeclaredAccessibility != Accessibility.Public)
                continue;
            AppendEvent(sb, ev);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendEvent(StringBuilder sb, IEventSymbol ev)
    {
        var typeName = ev.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        sb.Append("    public event ").Append(typeName).Append(' ').Append(ev.Name)
          .AppendLine()
          .AppendLine("    {")
          .AppendLine("        add => __inner." + ev.Name + " += value;")
          .AppendLine("        remove => __inner." + ev.Name + " -= value;")
          .AppendLine("    }");
    }

    private static void AppendProperty(StringBuilder sb, IPropertySymbol prop)
    {
        var typeName = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        sb.Append("    public ").Append(typeName).Append(' ').Append(prop.Name).AppendLine()
          .AppendLine("    {");
        if (prop.GetMethod is not null)
        {
            sb.Append("        get").AppendLine()
              .AppendLine("        {")
              .AppendLine("            return __inner." + prop.Name + ";")
              .AppendLine("        }");
        }
        if (prop.SetMethod is not null)
        {
            sb.Append("        set").AppendLine()
              .AppendLine("        {")
              .AppendLine("            __inner." + prop.Name + " = value;")
              .AppendLine("        }");
        }
        sb.AppendLine("    }");
    }

    private static void AppendMethod(StringBuilder sb, IMethodSymbol method)
    {
        if (method.Parameters.Any(p => p.RefKind != RefKind.None)) return;

        var isGenericTask = method.ReturnType is INamedTypeSymbol nts && nts.IsGenericType && IsType(nts.ConstructedFrom, "System.Threading.Tasks.Task");
        var isTask = method.ReturnType is INamedTypeSymbol nts0 && !nts0.IsGenericType && IsType(nts0, "System.Threading.Tasks.Task");
        var isGenericValueTask = method.ReturnType is INamedTypeSymbol nts2 && nts2.IsGenericType && IsType(nts2.ConstructedFrom, "System.Threading.Tasks.ValueTask");
        var isValueTask = method.ReturnType is INamedTypeSymbol nts3 && !nts3.IsGenericType && IsType(nts3, "System.Threading.Tasks.ValueTask");

        var returnType = method.ReturnType
            .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier))
            .Replace("global::", string.Empty);
        var methodName = method.Name;
        var typeFullName = method.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", string.Empty);
        var typeParams = method.TypeParameters.Length > 0 ? "<" + string.Join(", ", method.TypeParameters.Select(tp => tp.Name)) + ">" : string.Empty;
        var paramList = string.Join(", ", method.Parameters.Select(FormatParameter));
        var argList = string.Join(", ", method.Parameters.Select(p => p.Name));

        sb.Append("    public ").Append(returnType).Append(' ').Append(methodName).Append(typeParams)
          .Append('(').Append(paramList).Append(')').AppendLine()
          .AppendLine("    {");

        if (method.Parameters.Length > 0)
        {
            sb.AppendLine("        var __argsDict = new global::System.Collections.Generic.Dictionary<string, object?>(" + method.Parameters.Length + ");");
            foreach (var p in method.Parameters)
            {
                sb.Append("        __argsDict[\"").Append(p.Name).Append("\"] = ").Append(p.Name).AppendLine(";");
            }
            sb.AppendLine("        var __args = global::SourceGenerator.Runtime.JsonUtil.ToJson(__argsDict);");
        }
        else
        {
            sb.AppendLine("        string? __args = null;");
        }

        sb.AppendLine("        var __logMethod = (__inner.GetType().FullName ?? \"" + typeFullName + "\") + \"." + methodName + "\";");

        // attempt to locate implementation method for runtime override scanning
        if (method.Parameters.Length == 0)
        {
            sb.AppendLine("        var __mi = __inner.GetType().GetMethod(\"" + methodName + "\");");
        }
        else if (!method.Parameters.Any(p => p.Type is ITypeParameterSymbol))
        {
            var paramTypeList = string.Join(", ", method.Parameters.Select(p => "typeof(" + p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + ")"));
            sb.AppendLine("        var __mi = __inner.GetType().GetMethod(\"" + methodName + "\", new global::System.Type[] { " + paramTypeList + " });");
        }
        else
        {
            sb.AppendLine("        global::System.Reflection.MethodInfo? __mi = null;");
            sb.AppendLine("        foreach (var __m in __inner.GetType().GetMethods()) { if (__m.Name == \"" + methodName + "\") { var __ps = __m.GetParameters(); if (__ps.Length == " + method.Parameters.Length + ") { __mi = __m; break; } } }");
        }

        sb.AppendLine("        var __logger = (__sp?.GetService(typeof(global::Microsoft.Extensions.Logging.ILoggerFactory)) as global::Microsoft.Extensions.Logging.ILoggerFactory)?.CreateLogger(\"SourceGenerator.Runtime.ProxyRuntime\");");

        // compile-time behaviors and options (from interface method attributes)
        var behaviorSnippets = new List<string> { "new global::SourceGenerator.Runtime.LoggingBehavior()" };
        var optionsSetters = new List<string>();
        foreach (var a in method.GetAttributes())
        {
            if (a.AttributeClass is not INamedTypeSymbol attrClass) continue;

            INamedTypeSymbol? proxyBase = null;
            for (var t = attrClass; t is not null; t = t.BaseType as INamedTypeSymbol)
            {
                var constructed = t.ConstructedFrom ?? t;
                var fullName = constructed.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                if (fullName.Contains(ProxyBehaviorAttributeMetadataName, StringComparison.Ordinal)) { proxyBase = t; break; }
            }
            if (proxyBase is null) continue;

            ITypeSymbol? behaviorTypeSymbol = null;
            INamedTypeSymbol? optionsTypeSymbol = null;
            if (proxyBase.IsGenericType)
            {
                if (proxyBase.TypeArguments.Length == 1)
                {
                    behaviorTypeSymbol = proxyBase.TypeArguments[0];
                }
                else if (proxyBase.TypeArguments.Length == 2)
                {
                    behaviorTypeSymbol = proxyBase.TypeArguments[0];
                    optionsTypeSymbol = proxyBase.TypeArguments[1] as INamedTypeSymbol;
                }
            }
            if (behaviorTypeSymbol is null) continue;
            var behaviorFull = behaviorTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            behaviorSnippets.Add($"new {behaviorFull}()");

            if (optionsTypeSymbol is not null)
            {
                var assigns = new List<string>();
                foreach (var kv in a.NamedArguments)
                {
                    var propName = kv.Key;
                    var prop = optionsTypeSymbol.GetMembers().OfType<IPropertySymbol>().FirstOrDefault(p => p.Name == propName && !p.IsReadOnly);
                    if (prop is null) continue;
                    var lit = ToCSharpLiteral(kv.Value);
                    if (lit is null) continue;
                    assigns.Add(propName + " = " + lit);
                }
                var optFull = optionsTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var init = assigns.Count > 0 ? " { " + string.Join(", ", assigns) + " }" : string.Empty;
                optionsSetters.Add($"__ctx.SetFeature(new {optFull}{init});");
            }
        }
        sb.AppendLine("        var __behaviorsList = new global::System.Collections.Generic.List<global::SourceGenerator.Runtime.IInvocationBehavior> { " + string.Join(", ", behaviorSnippets) + " };");
        sb.AppendLine("        var __implOptions = new global::System.Collections.Generic.List<object>();");
        sb.AppendLine("        if (__mi is not null)");
        sb.AppendLine("        {");
        sb.AppendLine("            var __attrs = __mi.GetCustomAttributes(inherit: false);");
        sb.AppendLine("            foreach (var __attr in __attrs)");
        sb.AppendLine("            {");
        sb.AppendLine("                var __t = __attr.GetType();");
        sb.AppendLine("                var __bt = __t;");
        sb.AppendLine("                global::System.Type? __behaviorType = null;");
        sb.AppendLine("                global::System.Type? __optionsType = null;");
        sb.AppendLine("                while (__bt is not null)");
        sb.AppendLine("                {");
        sb.AppendLine("                    if (__bt.IsGenericType)");
        sb.AppendLine("                    {");
        sb.AppendLine("                        var __gdef = __bt.GetGenericTypeDefinition();");
        sb.AppendLine("                        if (__gdef == typeof(global::SourceGenerator.Abstraction.Attributes.ProxyBehaviorAttribute<>)) { __behaviorType = __bt.GetGenericArguments()[0]; break; }");
        sb.AppendLine("                        if (__gdef == typeof(global::SourceGenerator.Abstraction.Attributes.ProxyBehaviorAttribute<,>)) { var __ga = __bt.GetGenericArguments(); __behaviorType = __ga[0]; __optionsType = __ga[1]; break; }");
        sb.AppendLine("                    }");
        sb.AppendLine("                    __bt = __bt.BaseType!;");
        sb.AppendLine("                }");
        sb.AppendLine("                if (__behaviorType is null) continue;");
        sb.AppendLine("                var __inst = (global::SourceGenerator.Runtime.IInvocationBehavior?)global::System.Activator.CreateInstance(__behaviorType);");
        sb.AppendLine("                if (__inst is null) continue;");
        sb.AppendLine("                var __replaced = false;");
        sb.AppendLine("                for (int __i = 0; __i < __behaviorsList.Count; __i++)");
        sb.AppendLine("                {");
        sb.AppendLine("                    if (__behaviorsList[__i].GetType() == __behaviorType) { __behaviorsList[__i] = __inst; __replaced = true; break; }");
        sb.AppendLine("                }");
        sb.AppendLine("                if (!__replaced) __behaviorsList.Add(__inst);");
        sb.AppendLine("                if (__optionsType is not null)");
        sb.AppendLine("                {");
        sb.AppendLine("                    var __opt = global::System.Activator.CreateInstance(__optionsType);");
        sb.AppendLine("                    if (__opt is not null)");
        sb.AppendLine("                    {");
        sb.AppendLine("                        var __srcProps = __t.GetProperties(global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Instance);");
        sb.AppendLine("                        var __dstProps = __optionsType.GetProperties(global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Instance);");
        sb.AppendLine("                        foreach (var __dp in __dstProps)");
        sb.AppendLine("                        {");
        sb.AppendLine("                            if (!__dp.CanWrite) continue;");
        sb.AppendLine("                            var __sp = global::System.Array.Find(__srcProps, p => p.Name == __dp.Name && p.CanRead);");
        sb.AppendLine("                            if (__sp is null) continue;");
        sb.AppendLine("                            try { var __val = __sp.GetValue(__attr); __dp.SetValue(__opt, __val); } catch { }");
        sb.AppendLine("                        }");
        sb.AppendLine("                        __implOptions.Add(__opt);");
        sb.AppendLine("                    }");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        var __hasReturn = isGenericTask || isGenericValueTask || (!isTask && !isValueTask && !method.ReturnsVoid);
        sb.AppendLine("        var __ctx = new global::SourceGenerator.Runtime.InvocationContext { Method = __logMethod, ArgsJson = __args, TraceId = global::System.Guid.CreateVersion7(), Log = true, HasReturnValue = " + (__hasReturn ? "true" : "false") + ", ServiceProvider = __sp, Logger = __logger, Behaviors = __behaviorsList.ToArray() };");
        foreach (var line in optionsSetters) sb.AppendLine("        " + line);
        sb.AppendLine("        foreach (var __o in __implOptions) __ctx.Features[__o.GetType()] = __o;");

        var runtime = "global::SourceGenerator.Runtime.ProxyRuntime";
        if (isTask)
        {
            sb.AppendLine($"        return {runtime}.ExecuteTask(__ctx, () => __inner.{methodName}{typeParams}({argList}));");
        }
        else if (isGenericTask)
        {
            var tArg = ((INamedTypeSymbol)method.ReturnType).TypeArguments[0]
                .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier));
            sb.AppendLine($"        return {runtime}.ExecuteAsync<{tArg}>(__ctx, () => new global::System.Threading.Tasks.ValueTask<{tArg}>( __inner.{methodName}{typeParams}({argList}) ) ).AsTask();");
        }
        else if (isValueTask)
        {
            sb.AppendLine($"        return new global::System.Threading.Tasks.ValueTask( {runtime}.ExecuteTask(__ctx, () => __inner.{methodName}{typeParams}({argList}).AsTask()) );");
        }
        else if (isGenericValueTask)
        {
            var tArg = ((INamedTypeSymbol)method.ReturnType).TypeArguments[0]
                .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier));
            sb.AppendLine($"        return new global::System.Threading.Tasks.ValueTask<{tArg}>( {runtime}.ExecuteAsync<{tArg}>(__ctx, () => __inner.{methodName}{typeParams}({argList}) ).AsTask() );");
        }
        else if (method.ReturnsVoid)
        {
            sb.AppendLine($"        {runtime}.Execute<object?>(__ctx, () => {{ __inner.{methodName}{typeParams}({argList}); return global::System.Threading.Tasks.ValueTask.FromResult<object?>(null); }});");
            sb.AppendLine("        return;");
        }
        else
        {
            sb.AppendLine($"        return {runtime}.Execute<{returnType}>(__ctx, () => global::System.Threading.Tasks.ValueTask.FromResult(__inner.{methodName}{typeParams}({argList})));\n");
        }

        sb.AppendLine("    }");
    }

    private static string? ToCSharpLiteral(TypedConstant c)
    {
        if (c.IsNull) return "null";
        if (c.Value is null) return null;
        var type = c.Type?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ?? c.Value.GetType().FullName;
        if (c.Value is string s)
        {
            var escaped = s.Replace("\\", "\\\\").Replace("\"", "\\\"");
            return $"\"{escaped}\"";
        }
        if (c.Value is bool b) return b ? "true" : "false";
        if (c.Value is char ch)
        {
            var esc = ch == '\'' ? "\\'" : ch.ToString();
            return $"'{esc}'";
        }
        if (c.Value is IFormattable f)
        {
            return f.ToString(null, System.Globalization.CultureInfo.InvariantCulture);
        }
        // enums and others
        if (c.Type is INamedTypeSymbol nts && nts.TypeKind == TypeKind.Enum)
        {
            var named = nts.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return named + "." + c.Value.ToString();
        }
        return c.Value.ToString();
    }

    private static string FormatParameter(IParameterSymbol p)
    {
        var type = p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", string.Empty);
        var @default = p.HasExplicitDefaultValue ? " = " + (p.ExplicitDefaultValue is null ? "null" : p.ExplicitDefaultValue is string s ? "\"" + s.Replace("\"", "\\\"") + "\"" : p.ExplicitDefaultValue.ToString()) : string.Empty;
        return type + " " + p.Name + @default;
    }

    private static bool IsType(ITypeSymbol t, string metadataName)
        => t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Contains(metadataName, StringComparison.Ordinal);

    private static string GetSafeHintName(INamedTypeSymbol type)
    {
        var ns = type.ContainingNamespace.IsGlobalNamespace ? "global" : type.ContainingNamespace.ToDisplayString().Replace('.', '_');
        return ns + "__" + type.Name + "+Proxy";
    }
}
