server {
    listen 80;
    listen [::]:80;
    server_name admin.example.com;
    return 301 https://admin.example.com$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name admin.example.com;

    ssl_certificate ssl/admin.example.com.pem;
    ssl_certificate_key ssl/admin.example.com.key;

    add_header Strict-Transport-Security "max-age=31536000" always;

    root /var/appdata/demo/adminapp;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
